//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT
    {
        public int eventID { get; set; }
        public string title { get; set; }
        public string summary { get; set; }
        public string coverImagePath { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public int day { get; set; }
        public int monthID { get; set; }
        public int year { get; set; }
        public System.DateTime eventDate { get; set; }
    }
}
