//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINANCIAL_REPORT
    {
        public int financialReportID { get; set; }
        public decimal totalAmountRaised { get; set; }
        public decimal totalAmountSpent { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public int year { get; set; }
        public string summary { get; set; }
    }
}
