//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINED_MEMBER
    {
        public int finedMemberID { get; set; }
        public Nullable<decimal> amountPaid { get; set; }
        public string summary { get; set; }
        public int constitutionID { get; set; }
        public int memberID { get; set; }
        public int monthID { get; set; }
        public int day { get; set; }
        public int year { get; set; }
        public bool isdeleted { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
    }
}
