//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINED_MEMBER
    {
        public int finedMemberID { get; set; }
        public Nullable<decimal> amountPaid { get; set; }
        public string summary { get; set; }
        public int constitutionID { get; set; }
        public int memberID { get; set; }
        public int monthID { get; set; }
        public int day { get; set; }
        public int year { get; set; }
        public bool isdeleted { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
    }
}
