//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENERAL_ATTENDANCE
    {
        public int generalAttendanceID { get; set; }
        public int monthID { get; set; }
        public int year { get; set; }
        public Nullable<int> totalMembersPresent { get; set; }
        public Nullable<int> totalMembersAbsent { get; set; }
        public Nullable<decimal> totalDuesPaid { get; set; }
        public Nullable<decimal> totalDuesExpected { get; set; }
        public Nullable<decimal> totalDuesBalance { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public string summary { get; set; }
        public int day { get; set; }
        public System.DateTime attendanceDate { get; set; }
    }
}
