//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER
    {
        public int memberID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public System.DateTime birthday { get; set; }
        public string imagePath { get; set; }
        public string houseAddress { get; set; }
        public string emailAddress { get; set; }
        public Nullable<System.DateTime> membershipDate { get; set; }
        public int countryID { get; set; }
        public int nationalityID { get; set; }
        public int professionID { get; set; }
        public int positionID { get; set; }
        public int genderID { get; set; }
        public int employmentStatusID { get; set; }
        public int maritalStatusID { get; set; }
        public int permissionID { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public string phoneNumber { get; set; }
        public string phoneNumber2 { get; set; }
        public string phoneNumber3 { get; set; }
        public int membershipStatusID { get; set; }
        public System.DateTime deadDate { get; set; }
        public string nextOfKin { get; set; }
        public string LGAOfCountryOrigin { get; set; }
        public int relationshipToKinID { get; set; }
    }
}
