//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER
    {
        public int memberID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public System.DateTime birthday { get; set; }
        public string imagePath { get; set; }
        public string houseAddress { get; set; }
        public string emailAddress { get; set; }
        public Nullable<System.DateTime> membershipDate { get; set; }
        public int countryID { get; set; }
        public int nationalityID { get; set; }
        public int professionID { get; set; }
        public int positionID { get; set; }
        public int genderID { get; set; }
        public int employmentStatusID { get; set; }
        public int maritalStatusID { get; set; }
        public int permissionID { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public string phoneNumber { get; set; }
        public string phoneNumber2 { get; set; }
        public string phoneNumber3 { get; set; }
        public int membershipStatusID { get; set; }
        public System.DateTime deadDate { get; set; }
        public string nextOfKin { get; set; }
        public string LGAOfCountryOrigin { get; set; }
        public int relationshipToKinID { get; set; }
    }
}
