//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAL_ATTENDANCE
    {
        public int attendanceID { get; set; }
        public int attendanceStatusID { get; set; }
        public int memberID { get; set; }
        public Nullable<decimal> monthlyDues { get; set; }
        public Nullable<int> day { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public int monthID { get; set; }
        public int year { get; set; }
        public Nullable<decimal> expectedMonthlyDue { get; set; }
        public Nullable<decimal> balance { get; set; }
        public int generalAttendanceID { get; set; }
    }
}
