//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIAL_CONTRIBUTORS
    {
        public int specialContributorID { get; set; }
        public int memberID { get; set; }
        public decimal amountContributed { get; set; }
        public System.DateTime contributedDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public string summary { get; set; }
        public int specialContributionID { get; set; }
    }
}
