//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIAL_CONTRIBUTIONS
    {
        public int specialContributionID { get; set; }
        public string title { get; set; }
        public string summary { get; set; }
        public decimal amountToContribute { get; set; }
        public int supervisorID { get; set; }
        public System.DateTime contributionStartDate { get; set; }
        public System.DateTime contributionEndDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public decimal amountExpected { get; set; }
    }
}
