//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APC.Infrastructure.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APCEntities : DbContext
    {
        public APCEntities()
            : base("name=APCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ATTENDANCE_STATUS> ATTENDANCE_STATUS { get; set; }
        public virtual DbSet<CONSTITUTION> CONSTITUTION { get; set; }
        public virtual DbSet<COUNTRY> COUNTRY { get; set; }
        public virtual DbSet<DOCUMENT> DOCUMENT { get; set; }
        public virtual DbSet<DUAL_NATIONALITY> DUAL_NATIONALITY { get; set; }
        public virtual DbSet<EMPLOYMENT_STATUS> EMPLOYMENT_STATUS { get; set; }
        public virtual DbSet<EVENT_EXPENDITURE> EVENT_EXPENDITURE { get; set; }
        public virtual DbSet<EVENT_IMAGE> EVENT_IMAGE { get; set; }
        public virtual DbSet<EVENT_RECEIPTS> EVENT_RECEIPTS { get; set; }
        public virtual DbSet<EVENT_SALES> EVENT_SALES { get; set; }
        public virtual DbSet<EVENTS> EVENTS { get; set; }
        public virtual DbSet<EXPENDITURE> EXPENDITURE { get; set; }
        public virtual DbSet<FINANCIAL_REPORT> FINANCIAL_REPORT { get; set; }
        public virtual DbSet<FINED_MEMBER> FINED_MEMBER { get; set; }
        public virtual DbSet<GENDER> GENDER { get; set; }
        public virtual DbSet<GENERAL_ATTENDANCE> GENERAL_ATTENDANCE { get; set; }
        public virtual DbSet<MARITAL_STATUS> MARITAL_STATUS { get; set; }
        public virtual DbSet<MEMBER> MEMBER { get; set; }
        public virtual DbSet<MEMBERSHIP_STATUS> MEMBERSHIP_STATUS { get; set; }
        public virtual DbSet<MONTH> MONTH { get; set; }
        public virtual DbSet<NATIONALITY> NATIONALITY { get; set; }
        public virtual DbSet<NEXT_OF_KIN_RELATIONSHIP> NEXT_OF_KIN_RELATIONSHIP { get; set; }
        public virtual DbSet<PAYMENT_STATUS> PAYMENT_STATUS { get; set; }
        public virtual DbSet<PERMISSION> PERMISSION { get; set; }
        public virtual DbSet<PERSONAL_ATTENDANCE> PERSONAL_ATTENDANCE { get; set; }
        public virtual DbSet<POSITION> POSITION { get; set; }
        public virtual DbSet<PROFESSION> PROFESSION { get; set; }
        public virtual DbSet<SPECIAL_CONTRIBUTIONS> SPECIAL_CONTRIBUTIONS { get; set; }
        public virtual DbSet<SPECIAL_CONTRIBUTORS> SPECIAL_CONTRIBUTORS { get; set; }
        public virtual DbSet<RECEIPT> RECEIPT { get; set; }
    }
}
