//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APC.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_STATUS
    {
        public int paymentStatusID { get; set; }
        public string paymentStatusName { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
    }
}
