//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APC.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT
    {
        public int receiptID { get; set; }
        public string imagePath { get; set; }
        public string summary { get; set; }
        public string caption { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public System.DateTime receiptDate { get; set; }
        public decimal amoundSpet { get; set; }
    }
}
