//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APC.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIAL_CONTRIBUTORS
    {
        public int specialContributorID { get; set; }
        public int memberID { get; set; }
        public decimal amountContributed { get; set; }
        public System.DateTime contributedDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public string summary { get; set; }
        public int specialContributionID { get; set; }
    }
}
