//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APC.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIAL_CONTRIBUTIONS
    {
        public int specialContributionID { get; set; }
        public string title { get; set; }
        public string summary { get; set; }
        public decimal amountToContribute { get; set; }
        public int supervisorID { get; set; }
        public System.DateTime contributionStartDate { get; set; }
        public System.DateTime contributionEndDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public decimal amountExpected { get; set; }
    }
}
